#!/bin/sh
# SCRIPT DE SAUVETAGE - NETTOYAGE COMPLET

cmake -G "Unix Makefiles" \
  -DFAMILY=rp2040 \
  -DPICO_BOARD=pico \
  -DPICO_USB_HOST_DP_PIN=6 \
  -DPICO_USB_HOST_DM_PIN=7 \
  -DPIO_USB_DP_PIN=6 \
  -DPIO_USB_VBUS_PIN=-1 \
  -DCONFIG_USB=1 \
  -DSKIP_SPI_INIT=1 \
  -DSKIP_I2C_INIT=1 \
  -B build
